"""Unified Gradio web interface for AI Detector."""

import logging
from pathlib import Path

import gradio as gr

logger = logging.getLogger(__name__)

# ── Image detection tab ──────────────────────────────────────────────


def _get_image_detector():
    """Lazy-load and cache the ImageDetector singleton."""
    if not hasattr(_get_image_detector, "_instance"):
        from ai_detector.image.detector import ImageDetector

        det = ImageDetector()
        det.load_models()
        _get_image_detector._instance = det
    return _get_image_detector._instance


def classify_uploaded_image(uploaded_image: str) -> str:
    """Classify an uploaded image via the Gradio interface."""
    if uploaded_image is None:
        return "No image uploaded."
    from PIL import Image

    detector = _get_image_detector()
    image = Image.open(uploaded_image).convert("RGB")
    return detector.classify_image(image, uploaded_image)


# ── Audio detection tab ──────────────────────────────────────────────


def _get_audio_components():
    """Lazy-load and cache the AudioProcessor + DeepfakeDetector singletons."""
    if not hasattr(_get_audio_components, "_instances"):
        from ai_detector.audio.processor import AudioProcessor
        from ai_detector.audio.detector import DeepfakeDetector

        proc = AudioProcessor()
        det = DeepfakeDetector()
        det.load_model()
        _get_audio_components._instances = (proc, det)
    return _get_audio_components._instances


def classify_uploaded_audio(uploaded_audio: str) -> str:
    """Classify an uploaded audio file via the Gradio interface."""
    if uploaded_audio is None:
        return "No audio uploaded."

    processor, detector = _get_audio_components()
    path = Path(uploaded_audio)

    features = processor.extract_features(path)
    result = detector.predict(features)
    metadata = processor.get_metadata(path)

    lines = [
        f"🎵 Audio: {path.name}",
        f"📊 Duration: {metadata.duration:.2f}s | Sample Rate: {metadata.sample_rate} Hz | "
        f"Channels: {metadata.channels} | Format: {metadata.format}",
        "",
        f"{result['message']}",
        "",
        f"🤖 Deepfake Probability: {result['deepfake_probability'] * 100:.1f}%",
        f"✅ Authentic Probability: {result['authentic_probability'] * 100:.1f}%",
        f"📈 Confidence: {result['confidence'] * 100:.1f}%",
    ]
    return "\n".join(lines)


# ── Build Gradio app ─────────────────────────────────────────────────


def build_app() -> gr.Blocks:
    """Build the unified Gradio Blocks application."""
    with gr.Blocks(
        title="AI Detector",
        theme=gr.themes.Soft(),
    ) as app:
        gr.Markdown(
            "# 🛡️ AI Detector\n"
            "Detect AI-generated **images**, **videos**, and **deepfake audio** in one place."
        )

        with gr.Tab("🖼️ Image Detection"):
            gr.Markdown("Upload an image to determine if it was generated by AI.")
            with gr.Row():
                img_input = gr.Image(type="filepath", label="Upload Image")
                img_output = gr.Textbox(label="Results", lines=8)
            img_btn = gr.Button("Analyze Image", variant="primary")
            img_btn.click(
                fn=classify_uploaded_image, inputs=img_input, outputs=img_output
            )

        with gr.Tab("🎵 Audio Detection"):
            gr.Markdown("Upload an audio file to check if it is a deepfake.")
            with gr.Row():
                audio_input = gr.Audio(type="filepath", label="Upload Audio")
                audio_output = gr.Textbox(label="Results", lines=8)
            audio_btn = gr.Button("Analyze Audio", variant="primary")
            audio_btn.click(
                fn=classify_uploaded_audio, inputs=audio_input, outputs=audio_output
            )

    return app


def launch_app():
    """Build and launch the Gradio app."""
    app = build_app()
    app.launch()


if __name__ == "__main__":
    launch_app()
